package Visual;


import Datos.DatosTex;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JAZ
 */
public class FrmTex extends javax.swing.JFrame {
    private String fuentes[];
    private DefaultListModel dlm;
    DatosTex datos=new DatosTex();
    /**
     * Creates new form FrmTex
     */
    public FrmTex()throws UnsupportedLookAndFeelException{
        fuentes = GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();
        dlm =new DefaultListModel();
        initComponents();
        lista.setModel(dlm);
        cargarComponentes();
        
    }
    
        private void cargarComponentes() {
            for(int i=5; i<=90;i=i+5){
                cmbTamaño.addItem(i);
            }
            for(String fuente:fuentes){
                dlm.addElement(fuente);
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnNegrita = new javax.swing.JButton();
        btnCursiva = new javax.swing.JButton();
        btnSubrayar = new javax.swing.JButton();
        btnIz = new javax.swing.JButton();
        btnCentrado = new javax.swing.JButton();
        btnDe = new javax.swing.JButton();
        btnJustificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbTamaño = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGuardarMousePressed(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnAbrir.setText("Abrir");
        btnAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAbrirMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAbrirMousePressed(evt);
            }
        });
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        btnNegrita.setText("Negrita");
        btnNegrita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNegritaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNegritaMousePressed(evt);
            }
        });
        btnNegrita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegritaActionPerformed(evt);
            }
        });

        btnCursiva.setText("Cursiva");
        btnCursiva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCursivaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCursivaMousePressed(evt);
            }
        });

        btnSubrayar.setText("Subrayar");
        btnSubrayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubrayarMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSubrayarMousePressed(evt);
            }
        });

        btnIz.setText("Ali_Iz");
        btnIz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIzMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnIzMousePressed(evt);
            }
        });

        btnCentrado.setText("Centrado");
        btnCentrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCentradoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCentradoMousePressed(evt);
            }
        });

        btnDe.setText("Ali_De");
        btnDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDeMousePressed(evt);
            }
        });

        btnJustificar.setText("Justificar");
        btnJustificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnJustificarMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnJustificarMousePressed(evt);
            }
        });

        jLabel1.setText("Tamaño:");

        cmbTamaño.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTamañoItemStateChanged(evt);
            }
        });

        jLabel2.setText("Fuentes:");

        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lista);

        jScrollPane3.setViewportView(txtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(btnCursiva)
                    .addComponent(btnSubrayar)
                    .addComponent(btnIz)
                    .addComponent(btnCentrado)
                    .addComponent(btnDe)
                    .addComponent(btnJustificar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAbrir)
                    .addComponent(btnNegrita))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAbrir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNegrita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCursiva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSubrayar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCentrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnJustificar)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmbTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel2)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTamañoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTamañoItemStateChanged
        Font f= txtArea.getFont();
        txtArea.setFont(new Font(f.getName(),Font.PLAIN,Integer.parseInt(String.valueOf(cmbTamaño.getSelectedItem()))));
    }//GEN-LAST:event_cmbTamañoItemStateChanged

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged
        Font f= txtArea.getFont();
        txtArea.setFont(new Font(String.valueOf(dlm.getElementAt(lista.getSelectedIndex())),Font.PLAIN,f.getSize()));
    }//GEN-LAST:event_listaValueChanged

    private void btnAbrirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMousePressed
        datos.abrir(txtArea);
        
    }//GEN-LAST:event_btnAbrirMousePressed

    private void btnNegritaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNegritaMousePressed
        Font f = txtArea.getFont();
        txtArea.setFont(new Font(f.getName(), Font.BOLD, f.getSize()));
    }//GEN-LAST:event_btnNegritaMousePressed

    private void btnCursivaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCursivaMousePressed
        Font f = txtArea.getFont();
        txtArea.setFont(new Font(f.getName(), Font.ITALIC, f.getSize()));
    }//GEN-LAST:event_btnCursivaMousePressed

    private void btnSubrayarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubrayarMousePressed
        Font f = txtArea.getFont();
        txtArea.setFont(new Font(f.getName(), Font.PLAIN, f.getSize()));
    }//GEN-LAST:event_btnSubrayarMousePressed

    private void btnIzMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIzMousePressed
        StyledDocument doc = txtArea.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_LEFT);
        doc.setParagraphAttributes(0, doc.getLength(), center, false);
    }//GEN-LAST:event_btnIzMousePressed

    private void btnGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMousePressed
        datos.guardar(txtArea);
    }//GEN-LAST:event_btnGuardarMousePressed

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        btnGuardar.setToolTipText("Guardar");
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnAbrirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseEntered
        btnAbrir.setToolTipText("Abrir Archivo");
    }//GEN-LAST:event_btnAbrirMouseEntered

    private void btnNegritaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNegritaMouseEntered
        btnNegrita.setToolTipText("Negrita");
    }//GEN-LAST:event_btnNegritaMouseEntered

    private void btnCursivaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCursivaMouseEntered
        btnCursiva.setToolTipText("Cursiva");
    }//GEN-LAST:event_btnCursivaMouseEntered

    private void btnSubrayarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubrayarMouseEntered
        btnSubrayar.setToolTipText("Subrayar");
    }//GEN-LAST:event_btnSubrayarMouseEntered

    private void btnIzMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIzMouseEntered
        btnIz.setToolTipText("Izquierda");
    }//GEN-LAST:event_btnIzMouseEntered

    private void btnCentradoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCentradoMouseEntered
        btnCentrado.setToolTipText("Centrar");
    }//GEN-LAST:event_btnCentradoMouseEntered

    private void btnDeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeMouseEntered
         btnDe.setToolTipText("Derecha");
    }//GEN-LAST:event_btnDeMouseEntered

    private void btnJustificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJustificarMouseEntered
        btnJustificar.setToolTipText("Justificar");
    }//GEN-LAST:event_btnJustificarMouseEntered

    private void btnCentradoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCentradoMousePressed
       StyledDocument doc = txtArea.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
        doc.setParagraphAttributes(0, doc.getLength(), center, false);
    }//GEN-LAST:event_btnCentradoMousePressed

    private void btnDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeMousePressed
      StyledDocument doc = txtArea.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_RIGHT);
        doc.setParagraphAttributes(0, doc.getLength(), center, false);  
    }//GEN-LAST:event_btnDeMousePressed

    private void btnJustificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJustificarMousePressed
        StyledDocument doc = txtArea.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_JUSTIFIED);
        doc.setParagraphAttributes(0, doc.getLength(), center, false);
    }//GEN-LAST:event_btnJustificarMousePressed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNegritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegritaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNegritaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    try{
                        new FrmTex().setVisible(true);
                    }catch(UnsupportedLookAndFeelException ex){
                        Logger.getLogger(FrmTex.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnCentrado;
    private javax.swing.JButton btnCursiva;
    private javax.swing.JButton btnDe;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIz;
    private javax.swing.JButton btnJustificar;
    private javax.swing.JButton btnNegrita;
    private javax.swing.JButton btnSubrayar;
    private javax.swing.JComboBox cmbTamaño;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList lista;
    private javax.swing.JTextPane txtArea;
    // End of variables declaration//GEN-END:variables


    
}
